#!/usr/bin/python3

#Author :: z3r0day
#https://github.com/SxNade/SMTP-USER-BRTFRCE

RED = '\033[1;31;48m'
WHITE = "\33[0m"
GREEN = '\033[1;32;48m'


#SMTP USER BRUTEFORCE

import socket
import sys
import os
import time
#importing the required libraries

golo = '''
                            ,--.
                           {    }
                           K,   }
                          /  ~Y`
                     ,   /   /
                    {_'-K.__/
                      `/-.__L._
                      /  ' /`\_}
                     /  ' /
             ____   /  ' /
      ,-'~~~~    ~~/  ' /_
    ,'             ``~~~  ',
   (                        Y
  {                         I
 {      -                    `,
 |       ',                   )
 |        |   ,..__      __. Y
 |    .,_./  Y ' / ^Y   J   )|
 \           |' /   |   |   ||
  \          L_/    . _ (_,.'(
   \,   ,      ^^""' / |      )
     \_  \          /,L]     /
       '-_~-,       ` `   ./`
          `'{_            )
              ^^\..___,.--`  
'''


#conditional statement for grabing [sys] arguments for username and ip address

print(golo)
time.sleep(1)
print("\n (v2.0) starting...")
time.sleep(2)

#check for correct number of arguments
if len(sys.argv) != 3:
	print(colored("\n Usage:: ./usr25 <target-ip> <wordlist> \n", 'white', attrs=['reverse', 'blink']))
	sys.exit(0)

target_ip = sys.argv[1]
user_file = sys.argv[2]
#grabbing the necessary arguments

#check if the given file exists on the system
if os.path.exists(user_file) == False:
	print(colored('[!]File Not Found....exiting now..!', 'red', attrs=['bold']))
	sys.exit(0)
def brute(ip, wordlist):
	with open(wordlist, 'r') as file:
		for line in file.readlines():
			try:
				user = line.strip()
				#socket connection
				s = socket.socket()
				s.connect((ip, 25))
				s.recv(1024)
				#here comes the command
				s.send(f'VRFY {user}\r\n'.encode())
				answer = s.recv(1024).decode()
				if not "unknown" in answer.lower():
					print(colored(f"[+] {user} does exist", 'green', attrs=['bold']))
				s.close()
			except KeyboardInterrupt:
				input = f"[{RED}!{WHITE} Do you want to end bruteforce? (y/n)]"
				if input.lower() == 'y':
					print(f"[{GREEN}+{WHITE} Exiting.....]")
					sys.exit(0)
				else:
					pass


brute(ip, user_file)
